version: '3.8'

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile.webapp
    volumes:
      - ./instance:/app/instance
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development

  proxy:
    build:
      context: .
      dockerfile: Dockerfile.proxy
    volumes:
      - ./instance:/app/instance
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=development
